apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: trading-wizard
  labels:
    app: trading-wizard
    component: backend
type: Opaque
data:
  JWT_SECRET_KEY: Y2hhbmdlLXRoaXMtdG8tYS1zZWN1cmUtcmFuZG9tLXN0cmluZy1pbi1wcm9kdWN0aW9u
  DATABASE_URL: cG9zdGdyZXNxbDovL3RyYWRpbmdfd2l6YXJkOnRyYWRpbmdfd2l6YXJkXzIwMjRAcG9zdGdyZXMudHJhZGluZy13aXphcmQuc3ZjLmNsdXN0ZXIubG9jYWw6NTQzMi90cmFkaW5nX3dpemFyZA==
