apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trading-wizard-data
  namespace: trading-wizard
  labels:
    app.kubernetes.io/name: trading-wizard
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trading-wizard-cache
  namespace: trading-wizard
  labels:
    app.kubernetes.io/name: trading-wizard
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
